words = {
    "cat": 1,
    "dog": 1,
    "fish": 1,
    "apple": 1,
    "ball": 1,
    "house": 2,
    "school": 2,
    "tree": 2,
    "friend": 2,
    "computer": 3,
    "programming": 3,
    "language": 3,
    "chicken": 3,
    "celebrate": 4,
    "dinosaur": 4,
    "philosophy": 4,
    "challenge": 4,
    "understanding": 5,
    "universe": 5,
    "consciousness": 5,
    "mathematics": 5,
    "microprocessor": 5
}
